# Generated by Django 5.0.4 on 2024-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NGUOIDUNG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEN_DANG_NHAP', models.CharField(max_length=100)),
                ('HO_TEN', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=100)),
                ('SO_DIEN_THOAI', models.CharField(max_length=20)),
                ('MAT_KHAU', models.CharField(max_length=100)),
                ('NHAP_LAI_MAT_KHAU', models.CharField(max_length=100)),
                ('QUYEN', models.CharField(choices=[('user', 'Người dùng'), ('driver', 'Tài xế'), ('seller', 'Người bán')], max_length=10)),
            ],
        ),
    ]
