# Generated by Django 5.0.4 on 2024-05-12 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QUANAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tenquan",
                    models.CharField(
                        default="Chưa xác định tên quán ăn!", max_length=100
                    ),
                ),
                (
                    "tinhtrangdquan",
                    models.CharField(
                        choices=[("tinhtrang1", "Mở cửa"), ("tinhtrang2", "Đóng cửa")],
                        default="tinhtrang1",
                        max_length=255,
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DOAN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tendoan",
                    models.CharField(
                        default="Chưa xác định tên đồ ăn!", max_length=100
                    ),
                ),
                ("giamua", models.IntegerField(default=0)),
                (
                    "tinhtrangdoan",
                    models.CharField(
                        choices=[
                            ("tinhtrang1", "Còn hàng"),
                            ("tinhtrang2", "Hết hàng"),
                        ],
                        default="tinhtrang1",
                        max_length=255,
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenquanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.quanan"
                    ),
                ),
            ],
        ),
    ]
