# Generated by Django 5.0.4 on 2024-05-12 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_quanan_lat_quanan_var"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doan",
            old_name="tenquanan",
            new_name="quanan",
        ),
    ]
