# Generated by Django 5.0.4 on 2024-05-13 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0004_rename_tenquanan_doan_quanan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="quanan",
            name="nguoi_dung",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quanan",
            name="tinhtrangquan",
            field=models.CharField(
                choices=[("tinhtrang1", "Mở cửa"), ("tinhtrang2", "Đóng cửa")],
                default="tinhtrang2",
                max_length=255,
            ),
        ),
    ]
