# Generated by Django 5.0.4 on 2024-05-15 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_alter_quanan_nguoi_dung_alter_quanan_tinhtrangquan"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DONHANGDICHUYEN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ten_dang_nhap_tai_xe", models.CharField(max_length=100, null=True)),
                ("diem_don_lat", models.FloatField(default=0)),
                ("diem_don_var", models.FloatField(default=0)),
                ("diem_den_lat", models.FloatField(default=0)),
                ("diem_den_var", models.FloatField(default=0)),
                ("giaTien", models.IntegerField(default=0)),
                (
                    "tinhtrang",
                    models.CharField(
                        choices=[
                            ("tinhtrang1", "Chờ xác nhận"),
                            ("tinhtrang2", "Đã xác nhận"),
                            ("tinhtrang3", "Đã hủy"),
                            ("tinhtrang4", "Đang di chuyển"),
                            ("tinhtrang5", "Đã hoàn thành"),
                        ],
                        default="tinhtrang1",
                        max_length=255,
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
