# Generated by Django 5.0.4 on 2024-05-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_donhangdichuyen_diem_den_donhangdichuyen_diem_don"),
    ]

    operations = [
        migrations.AddField(
            model_name="donhangdichuyen",
            name="hoaHong",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="donhangdichuyen",
            name="vitritaixe",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="donhangdichuyen",
            name="vitritaixe_lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="donhangdichuyen",
            name="vitritaixe_var",
            field=models.FloatField(default=0),
        ),
    ]
