# Generated by Django 5.0.4 on 2024-05-17 19:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0008_donhangdichuyen_hoahong_donhangdichuyen_vitritaixe_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GioHang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("soluong", models.IntegerField(default=1)),
                (
                    "tinhtrang",
                    models.CharField(
                        choices=[
                            ("tinhtrang1", "Thêm vào giỏ hàng"),
                            ("tinhtrang2", "Đặt hàng"),
                            ("tinhtrang3", "Đã hủy"),
                            ("tinhtrang4", "Quán ăn xác nhận"),
                            ("tinhtrang5", "Tài xế xác nhận"),
                            ("tinhtrang6", "Quán ăn đang chuẩn bị"),
                            ("tinhtrang7", "Tài xế đang trên đường giao"),
                            ("tinhtrang8", "Đã hoàn thành"),
                        ],
                        default="tinhtrang1",
                        max_length=255,
                    ),
                ),
                (
                    "ngayMua",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 5, 18, 2, 30, 17, 737232)
                    ),
                ),
                (
                    "doan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.doan"
                    ),
                ),
                (
                    "nguoi_dung",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
