# Generated by Django 5.0.4 on 2024-05-17 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0009_giohang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giohang",
            name="ngayMua",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 18, 2, 32, 47, 246336)
            ),
        ),
    ]
