# Generated by Django 5.0.4 on 2024-05-17 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0010_alter_giohang_ngaymua"),
    ]

    operations = [
        migrations.AddField(
            model_name="giohang",
            name="tongTien",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="giohang",
            name="ngayMua",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 18, 3, 56, 45, 481144)
            ),
        ),
    ]
