# Generated by Django 5.0.4 on 2024-05-18 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0011_giohang_tongtien_alter_giohang_ngaymua"),
    ]

    operations = [
        migrations.AddField(
            model_name="giohang",
            name="diem_giao",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="giohang",
            name="diem_giao_lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="diem_giao_var",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="hoaHong",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="ten_dang_nhap_tai_xe",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="giohang",
            name="thanhTien",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="tienship",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="vitritaixe",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="giohang",
            name="vitritaixe_lat",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="giohang",
            name="vitritaixe_var",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="giohang",
            name="ngayMua",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 18, 17, 23, 18, 979594)
            ),
        ),
    ]
