# Generated by Django 5.0.4 on 2024-05-18 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0012_giohang_diem_giao_giohang_diem_giao_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quanan",
            name="vitriquan",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="giohang",
            name="ngayMua",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 18, 18, 29, 21, 438550)
            ),
        ),
    ]
